# Generated by Django 4.2.3 on 2023-07-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("DepartmentId", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("EmployeeID", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeeName", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("DateOfJoining", models.DateField()),
                ("PhotoFileName", models.CharField(max_length=100)),
            ],
        ),
    ]
